spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.data.mongodb.uri=mongodb+srv://admin:${MONGODB_PASSWORD}@cluster0.o7zag.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}